### PR TITLE
Update peerDependencies to support Grunt 1.0

### PR DESCRIPTION
**Pull request by gruntjs-updater**
Update peerDependencies to support Grunt 1.0

Hello,

This is an automated issue request to update the `peerDependencies` for your Grunt plugin.
We ask you to merge this and **publish a new release on npm** to get your plugin working in Grunt 1.0!

Read more here: http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#peer-dependencies
Also on Twitter: https://twitter.com/gruntjs/status/700819604155707392

If you have any questions or you no longer have time to maintain this plugin, then please let us know in this thread.

Thanks for creating and working on this plugin!

(P.S. Close this PR if it is a mistake, sorry)

### CODE REVIEW

**Comment by XVincentX** [comment]
@vojtajina 
Is there anything blocking you from merging this? That would really help the community to move forward!

**Comment by AtiX** [comment]
+1

**Comment by hildjj** [comment]
@vojtajina if you don't have time to update grunt-coffeelint, I'm happy to help.

**Comment by XVincentX** [comment]
That's sad. We're just one click away to make this happen and it does not 👎

**Comment by sparanoid** [comment]
@vojtajina ping, could you merge this PR and publish a new release? This is a breaking change.

**Comment by pkubowicz** [comment]
Don't be silly, it should be obvious after 2 months that this project is dead and noone will ever respond. The only was is to make a fork. Anyone is willing to?

**Comment by XVincentX** [comment]
Who! If you could now create a npm release, we should be done here.

**Comment by mwittig** [comment]
@XVincentX Will do asap.

**Pull request merged**
